### ISSUE TITLE
Remove scala-library from POM of java client

### ISSUE THREAD

**Issue by maesenka** [WegenenVerkeer/RxHttpClient#5]
Maven's dependency resolution also pulls in scala libs for the Java client.

**Comment by maesenka** [comment]
Possible solution discussed here: http://stackoverflow.com/questions/9679684/sbt-how-to-prevent-scala-library-from-being-added-to-pom-automatically

**Comment by joachimvda** [comment]
In maven wou je dit oplossen door provided scope te gebruiken. Misschien 
kent sbt ook zo'n scope.

**Comment by maesenka** [comment]
Solved in commit 4082b20c135c1d1179080d70b0c9a57924b4be5a
